# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-20 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0002_auto_20190920_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='granted',
            field=models.BooleanField(default=False),
        ),
    ]
